### PR TITLE
Now not capturing keys to avoid conflicting with the developer's code

### LINKED ISSUE #79: Do not capture `space` and other keys by default.
Currently, the space key toggles between normal and vr mode but it is not documented and it can interfer with a game custom controls.

`p` and `v` keys also map to unexpected functionality. Instead we should document the API and let the developers to use it.

### PR DESCRIPTION
**Pull request by delapuente**
Fix #79

### CODE REVIEW

**Comment by caseyyee** [comment]
Great thanks!

File: Assets/WebGLTemplates/WebVR/webvr.js [hunk 1]
```diff
@@ -169,16 +169,14 @@
...
-      testTimeStart = performance.now();
-      gameInstance.SendMessage('WebVRCameraSet', 'TestTime');
-    }
+  function togglePerf() {
+    gameInstance.SendMessage('WebVRCameraSet', 'TogglePerf');
+  }
+
+  function testRoundtripTime() {
+    console.log("Testing roundtrip time...");
+    testTimeStart = performance.now();
```
Comment (cvan) [inline Assets/WebGLTemplates/WebVR/webvr.js]: FYI: we probably ought to [polyfill](https://gist.github.com/paulirish/5438650) `performance.now` just in case

Comment (caseyyee) [reply Assets/WebGLTemplates/WebVR/webvr.js]: Support seems pretty good?
https://caniuse.com/#search=performance.now

Comment (cvan) [reply Assets/WebGLTemplates/WebVR/webvr.js]: oh, guess you're right – I'm living in the past 👴 heh
